trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'  # Or 'Debug' or 'Staging' - YOU MUST CHOOSE
  appServiceName: 'AjTollSystem' #  <-- Correct App Service name
  resourceGroupName: 'AjTollSystem' # <--- Resource group name
  azureSubscriptionName: 'ServiceConnection' # <--- Service connection name

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet tool installer'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true # <--- Add this line: zip the publish output

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    TargetPath: '$(Build.ArtifactStagingDirectory)' # Added TargetPath
    ArtifactName: 'drop'
    publishLocation: 'pipeline' # Changed to 'pipeline'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscriptionName)'
    appType: 'webApp'
    appName: '$(appServiceName)' # Correct App Service name
    resourceGroupName: '$(resourceGroupName)' 
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip' # <--- Correct path
    deploymentMethod: 'zipDeploy'