# build-test-artifact.yml
trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  appServiceName: 'AjTollSystem'
  resourceGroupName: 'AjTollSystem'
  azureSubscriptionName: 'ServiceConnection'

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet tool installer'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Install EF Core CLI"
  inputs:
    command: custom
    custom: tool
    arguments: install --global dotnet-ef --version 9.*

- task: AzureCLI@2
  displayName: 'Connect to Azure'
  inputs:
    azureSubscription: 'ServiceConnection' # The name of your service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: | 
      echo "Successfully connected to Azure."

- task: DotNetCoreCLI@2
  displayName: 'Database migrations'
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: 'database update --context Persistence.Contexts.Context --configuration $(buildConfiguration) --project Persistence --startup-project Api --connection "$(DatabaseConnection)"'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: 'Api/Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    TargetPath: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
