trigger: none  # This pipeline does not trigger on its own commits

resources:
  pipelines:
  - pipeline: buildAndTest      # local reference name
    source: build-test-artifact # name of your build pipeline
    trigger: true               # triggers this pipeline on every new successful run

pool:
  vmImage: 'windows-latest'

variables:
  appServiceName: 'AjTollSystem'
  resourceGroupName: 'AjTollSystem'
  azureSubscriptionName: 'ServiceConnection'

steps:
- download: buildAndTest
  artifact: drop  # must match ArtifactName in build pipeline
  displayName: 'Download build artifacts'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscriptionName)'
    appType: 'webApp'
    appName: '$(appServiceName)'
    resourceGroupName: '$(resourceGroupName)'
    package: '$(Pipeline.Workspace)\buildAndTest\drop\Api.zip'
    deploymentMethod: 'zipDeploy'