// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250808231537_change-simulated-api-logic")]
    partial class changesimulatedapilogic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Entities.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccumulatedFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("Persistence.Entities.FeeInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("FeeInterval");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new TimeSpan(0, 6, 30, 0, 0),
                            Fee = 9m,
                            Start = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            End = new TimeSpan(0, 15, 0, 0, 0),
                            Fee = 9m,
                            Start = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            End = new TimeSpan(0, 18, 30, 0, 0),
                            Fee = 9m,
                            Start = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            End = new TimeSpan(0, 7, 0, 0, 0),
                            Fee = 16m,
                            Start = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            End = new TimeSpan(0, 8, 30, 0, 0),
                            Fee = 16m,
                            Start = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            End = new TimeSpan(0, 15, 30, 0, 0),
                            Fee = 16m,
                            Start = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Fee = 16m,
                            Start = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            End = new TimeSpan(0, 8, 0, 0, 0),
                            Fee = 22m,
                            Start = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            End = new TimeSpan(0, 17, 0, 0, 0),
                            Fee = 22m,
                            Start = new TimeSpan(0, 15, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("Persistence.Entities.MonthlyFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccumulatedFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonthlyFee");
                });

            modelBuilder.Entity("Persistence.Entities.SimulatedVehicleApiData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SimulatedVehicleApiData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OwnerName = "Tommy Tjernqvist",
                            PlateNumber = "PTP461",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 2,
                            OwnerName = "Hugo Håkman",
                            PlateNumber = "FJN740",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 3,
                            OwnerName = "Linda Längström",
                            PlateNumber = "ZCX563",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 4,
                            OwnerName = "Kalle Krantz",
                            PlateNumber = "VAT087",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 5,
                            OwnerName = "Benny Bäckström",
                            PlateNumber = "CUL352",
                            VehicleTypeName = "Bus"
                        },
                        new
                        {
                            Id = 6,
                            OwnerName = "Ronny Röjberg",
                            PlateNumber = "UXL821",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 7,
                            OwnerName = "Sally Ståhl",
                            PlateNumber = "MKW921",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 8,
                            OwnerName = "Eddie Elg",
                            PlateNumber = "OLU514",
                            VehicleTypeName = "Military"
                        },
                        new
                        {
                            Id = 9,
                            OwnerName = "Felix Färnelund",
                            PlateNumber = "TJY229",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 10,
                            OwnerName = "Jörgen Järvstad",
                            PlateNumber = "UHA649",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 11,
                            OwnerName = "Lotta Löfgren",
                            PlateNumber = "BTS372",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 12,
                            OwnerName = "Gustav Gullberg",
                            PlateNumber = "XKL291",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 13,
                            OwnerName = "Mona Mörk",
                            PlateNumber = "PNY183",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 14,
                            OwnerName = "Oscar Olofsson",
                            PlateNumber = "KLM562",
                            VehicleTypeName = "Emergency"
                        },
                        new
                        {
                            Id = 15,
                            OwnerName = "Victor Vallén",
                            PlateNumber = "RMJ473",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 16,
                            OwnerName = "Jenny Järp",
                            PlateNumber = "QWE982",
                            VehicleTypeName = "Foreign"
                        },
                        new
                        {
                            Id = 17,
                            OwnerName = "Stina Sörlén",
                            PlateNumber = "TRP648",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 18,
                            OwnerName = "Axel Åkesson",
                            PlateNumber = "ZXC101",
                            VehicleTypeName = "Military"
                        },
                        new
                        {
                            Id = 19,
                            OwnerName = "Nina Norrström",
                            PlateNumber = "LPO839",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 20,
                            OwnerName = "Felicia Forslund",
                            PlateNumber = "GHT467",
                            VehicleTypeName = "Bus"
                        },
                        new
                        {
                            Id = 21,
                            OwnerName = "Greta Gerdman",
                            PlateNumber = "KLB381",
                            VehicleTypeName = "Tractor"
                        },
                        new
                        {
                            Id = 22,
                            OwnerName = "Erik Eklund",
                            PlateNumber = "XOP122",
                            VehicleTypeName = "Diplomat"
                        },
                        new
                        {
                            Id = 23,
                            OwnerName = "Beatrice Boström",
                            PlateNumber = "WZX771",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 24,
                            OwnerName = "Fredrik Friberg",
                            PlateNumber = "HUE294",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 25,
                            OwnerName = "Astrid Albinsson",
                            PlateNumber = "LPD450",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 26,
                            OwnerName = "Sigge Sandström",
                            PlateNumber = "PRT999",
                            VehicleTypeName = "Foreign"
                        },
                        new
                        {
                            Id = 27,
                            OwnerName = "Kajsa Källström",
                            PlateNumber = "KNL238",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 28,
                            OwnerName = "Torvald Tollberg",
                            PlateNumber = "UBK768",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 29,
                            OwnerName = "Lilly Lind",
                            PlateNumber = "EMG482",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 30,
                            OwnerName = "Bertil Bäckström",
                            PlateNumber = "JNH590",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 31,
                            OwnerName = "Hanna Hultgren",
                            PlateNumber = "JOL342",
                            VehicleTypeName = "Emergency"
                        },
                        new
                        {
                            Id = 32,
                            OwnerName = "Dagmar Dahlen",
                            PlateNumber = "WMD229",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 33,
                            OwnerName = "Oskar Odelberg",
                            PlateNumber = "TYC992",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 34,
                            OwnerName = "Clara Carlsson",
                            PlateNumber = "TRD147",
                            VehicleTypeName = "Motorcycle"
                        },
                        new
                        {
                            Id = 35,
                            OwnerName = "Harry Hägglund",
                            PlateNumber = "BXA321",
                            VehicleTypeName = "Military"
                        },
                        new
                        {
                            Id = 36,
                            OwnerName = "Elsa Eklund",
                            PlateNumber = "PLT465",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 37,
                            OwnerName = "Ulf Ulander",
                            PlateNumber = "GFX109",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 38,
                            OwnerName = "Märta Melin",
                            PlateNumber = "LSQ555",
                            VehicleTypeName = "Bus"
                        },
                        new
                        {
                            Id = 39,
                            OwnerName = "Simon Stenberg",
                            PlateNumber = "NKI211",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 40,
                            OwnerName = "Ingrid Irén",
                            PlateNumber = "FPZ830",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 41,
                            OwnerName = "Göran Gidlund",
                            PlateNumber = "TXR871",
                            VehicleTypeName = "Military"
                        },
                        new
                        {
                            Id = 42,
                            OwnerName = "Camilla Carlsson",
                            PlateNumber = "WQL130",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 43,
                            OwnerName = "Roland Rindberg",
                            PlateNumber = "BYH376",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 44,
                            OwnerName = "Lina Ljungholm",
                            PlateNumber = "ZCP591",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 45,
                            OwnerName = "Björn Björkman",
                            PlateNumber = "TDA643",
                            VehicleTypeName = "Bus"
                        },
                        new
                        {
                            Id = 46,
                            OwnerName = "Stella Sörensson",
                            PlateNumber = "CBX008",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 47,
                            OwnerName = "Einar Engström",
                            PlateNumber = "HKO483",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 48,
                            OwnerName = "Emilia Ekberg",
                            PlateNumber = "WLQ599",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 49,
                            OwnerName = "Kristian Karlsson",
                            PlateNumber = "YSQ102",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 50,
                            OwnerName = "Viola Vinge",
                            PlateNumber = "RGX702",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 51,
                            OwnerName = "Torsten Törnqvist",
                            PlateNumber = "MTF981",
                            VehicleTypeName = "Truck"
                        },
                        new
                        {
                            Id = 52,
                            OwnerName = "Ellinor Elm",
                            PlateNumber = "GQV753",
                            VehicleTypeName = "Car"
                        },
                        new
                        {
                            Id = 53,
                            OwnerName = "Sven Svahn",
                            PlateNumber = "HZX610",
                            VehicleTypeName = "Truck"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTollFree")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VehicleType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsTollFree = true,
                            TypeName = "Motorcycle"
                        },
                        new
                        {
                            Id = 2,
                            IsTollFree = true,
                            TypeName = "Tractor"
                        },
                        new
                        {
                            Id = 3,
                            IsTollFree = true,
                            TypeName = "Emergency"
                        },
                        new
                        {
                            Id = 4,
                            IsTollFree = true,
                            TypeName = "Diplomat"
                        },
                        new
                        {
                            Id = 5,
                            IsTollFree = true,
                            TypeName = "Foreign"
                        },
                        new
                        {
                            Id = 6,
                            IsTollFree = true,
                            TypeName = "Military"
                        },
                        new
                        {
                            Id = 7,
                            IsTollFree = false,
                            TypeName = "Car"
                        },
                        new
                        {
                            Id = 8,
                            IsTollFree = false,
                            TypeName = "Truck"
                        },
                        new
                        {
                            Id = 9,
                            IsTollFree = false,
                            TypeName = "Bus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
