global using AutoMapper;
global using Business.Interfaces;
global using Business.Services;
global using Microsoft.EntityFrameworkCore;
global using Persistence.Contexts;
global using Persistence.Interfaces;
global using Persistence.Services;
global using PublicHoliday;
global using System.Text.Json.Serialization;
